services:
  db:
    image: mariadb:11.8.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commerce-user
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "3306:3306"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
