services:
  app:
    image: user-service:latest
    container_name: user-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/commerce-user
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
    ports:
      - "8081:8081"
    networks:
      - commerce-net
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health/liveness" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s

networks:
  commerce-net:
    external: true
